from Lib import *
inOrderArr=[]
PreOrderArr=[]
PostOrderArr=[]
modo1 = modo(1)
modo2 = modo(2)
modo3 = modo(3)
modo4 =  modo(4)
modo5 = modo(5)
modo6 = modo(6)
modo7 = modo (7)
linkHijo(modo1,modo2,modo3)
linkHijo(modo2,modo4,modo5)
linkHijo(modo3,modo6,modo7)
LRV(modo1,PostOrderArr)
VLR(modo1,PreOrderArr)
LVR (modo1,inOrderArr)
print( inOrderArr )
print( PreOrderArr )
print( PostOrderArr)
print( modo1.getArbol())
modoRaiz = modo(16)
modo9 = modo(5)
modo10 = modo(7)
modo11 = modo(12)
modo12 =  modo(9)
modo13 = modo(20)
modo14 = modo(18)
modo15 = modo (3)
modo16 = modo(10)
modo17 = modo(14)
modoOrdenados(modoRaiz,modo9)
modoOrdenados(modoRaiz,modo10)
print(modoRaiz.getArbol())
